version: '8'
services:

  collector:
    image: otel/opentelemetry-collector-contrib:0.111.0
    command: [ "--config=/etc/otel-collector-config.yml" ]
    volumes:
      - ./otel-config.yml:/etc/otel-collector-config.yml
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - jaeger-service
      - elasticsearch
    networks:
      - elastic

  jaeger-service:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4317"
    networks:
      - elastic

  mockserver:
    image: dummy-mock-server:1.0
    ports:
      - "10180:10180"
    networks:
      - elastic

  springapp:
    image: sfelaco/spring:0.1
    ports:
      - "9090:9090"
    environment:
      - MOCK_ENDPOINT=http://mockserver:10180
      - OTEL_ENDOPOINT=http://collector:4317
    networks:
      - elastic

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.3
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms2g -Xmx5g
      - xpack.security.enabled=false # Disattiva la sicurezza per semplificare l'avvio
    ports:
      - "9200:9200"
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.3
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    networks:
      - elastic
    depends_on:
      - elasticsearch

  apm-server:
    image: docker.elastic.co/apm/apm-server:8.15.3
    container_name: apm-server
    ports:
      - 8200:8200
    user: apm-server
    volumes:
      - ./apm-server.docker.yml:/usr/share/apm-server/apm-server.yml:ro
    command: >
      --strict.perms=false
      -e
      -E output.elasticsearch.hosts=["elasticsearch:9200"]
    networks:
      - elastic
    depends_on:
      - elasticsearch
      - kibana

networks:
  elastic:
    driver: bridge
